In [1]:
import cv2 

In [2]:
image=cv2.imread('rebecca.jpg')
print(image)

[[[  1 255 255]
  [  1 255 255]
  [  1 255 255]
  ...
  [  1 255 255]
  [  1 255 255]
  [  1 255 255]]

 [[  1 255 255]
  [  1 255 255]
  [  1 255 255]
  ...
  [  1 255 255]
  [  1 255 255]
  [  1 255 255]]

 [[  1 255 255]
  [  1 255 255]
  [  1 255 255]
  ...
  [  1 255 255]
  [  1 255 255]
  [  1 255 255]]

 ...

 [[ 42  26  20]
  [ 45  29  23]
  [ 40  26  20]
  ...
  [ 26 181 237]
  [ 24 182 236]
  [ 26 181 236]]

 [[ 41  25  19]
  [ 51  35  29]
  [ 40  26  20]
  ...
  [ 23 180 236]
  [ 24 181 237]
  [ 26 181 236]]

 [[ 38  22  16]
  [ 48  32  26]
  [ 41  27  21]
  ...
  [ 23 180 236]
  [ 22 181 237]
  [ 24 182 236]]]


In [3]:
cv2.imshow('rebecca',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# my_img=cv2.imread('rebecca.jpg',0)
# cv2.imshow('Gray Scale Image Apple',my_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [5]:
# img=cv2.imread('rebecca.jpg')
# img1=cv2.resize(img,(250,250))
# cv2.imshow('resized',img1)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [6]:
# img1=cv2.imread('rebecca.jpg')
# img1=cv2.resize(img1,(250,250))
# img = cv2.copyMakeBorder(img1, 250, 250, 250, 250,cv2.BORDER_REFLECT)
# cv2.imshow('ADD' , img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [7]:
# from matplotlib import pyplot as plt
# img=cv2.imread('rebecca.jpg')
# img=cv2.resize(img,(250,250),0)
# start=(0,250)
# end=(250,0)
# thickness=10
# color=(250,0,0)
# image = cv2.line(img, start, end, color, thickness)
# cv2.imshow('Draw Line',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [8]:
# from matplotlib import pyplot as plt
# img=cv2.imread('rebecca.jpg')
# img=cv2.resize(img,(250,250))
# start=(0,0)
# end=(250,250)
# thickness=10
# color=(250,0,0)
# image = cv2.arrowedLine(img, start, end, color, thickness)
# start=(0,250)
# end=(250,0)
# thickness=10
# color=(250,0,0)
# image = cv2.arrowedLine(image, start, end, color, thickness)
# cv2.imshow('Draw Line',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [9]:
# from matplotlib import pyplot as plt
# img=cv2.imread('rebecca.jpg')
# img=cv2.resize(img,(250,250),0)
# thickness=5
# color=(250,0,0)
# center_coordinates=(150,125)
# axesLength=(100,100)
# angle=30
# startAngle=0
# endAngle=360
# color=(50,250,200)
# thickness=5
# image = cv2.ellipse(img, center_coordinates, axesLength, angle, startAngle, endAngle, color, thickness)
# cv2.imshow('Draw ellipse',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [10]:
# img[:, 0:50] = [255, 0, 0]
# cv2.imshow('grame',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [11]:
# img = cv2.imread('rebecca.jpg')
# my_roi = img[0:100, 0:100]
# img[300:400, 300:400] = [0,255,0]
# cv2.imshow('grame',img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [13]:
# import cv2
# import numpy as np
# img = cv2.imread("rebecca.jpg", 0)
# img=cv2.Canny(img, 50, 50)
# cv2.imshow('grame',img)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [14]:
# import cv2
# import numpy as np
# img = np.zeros((200, 200), dtype=np.uint8)
# img[50:150, 50:150] = 255
# ret, thresh = cv2.threshold(img, 127, 255, 0)
# contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
# color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
# img = cv2.drawContours(color, contours, -1, (0,255,0), 2)
# cv2.imshow("contours", color)
# cv2.waitKey()
# cv2.destroyAllWindows()


In [17]:
# import cv2
# import numpy as np
# img = cv2.imread('rebecca.jpg')
# img=cv2.resize(img,(800,500),0)
# gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# edges = cv2.Canny(gray, 50, 120)
# minLineLength = 20
# maxLineGap = 5
# lines = cv2.HoughLinesP(edges, 1, np.pi/180.0, 20,
#  minLineLength, maxLineGap)
# for x1, y1, x2, y2 in lines[0]:
#     cv2.line(img, (x1, y1), (x2, y2), (0,255,0),2)a
# cv2.imshow("edges", edges)
# cv2.imshow("lines", img)
# cv2.waitKey()
# cv2.destroyAllWindows()

In [19]:
# import cv2
# import numpy as np
# planets = cv2.imread('rebecca.jpg')
# gray_img = cv2.cvtColor(planets, cv2.COLOR_BGR2GRAY)
# gray_img = cv2.medianBlur(gray_img, 5)
# #cv2.approxPolyDP.
# circles = cv2.HoughCircles(gray_img,cv2.HOUGH_GRADIENT,1,120,param1=50,param2=50,minRadius=0,maxRadius=100)
# circles = np.uint16(np.around(circles))
# for i in circles[0,:]:
#  # draw the outer circle
#  cv2.circle(planets,(i[0],i[1]),i[2],(0,255,0),2)
#  # draw the center of the circle
#  cv2.circle(planets,(i[0],i[1]),2,(0,0,255),3)
# cv2.imwrite("rebecca.jpg", planets)
# cv2.imshow("HoughCirlces", planets)
# cv2.waitKey()
# cv2.destroyAllWindows()